# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    increment_build_number(xcodeproj: "Audiometer.xcodeproj")    
    build_app(workspace: "Audiometer.xcworkspace", scheme: "Audiometer",export_options: {
        provisioningProfiles: { 
          'com.AudiometerVideo.demo' => 'Audiometer-Ad-hoc'
        }})
  end
end

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :dysms do    
    download_dsyms(version: "1.3.2", build_number: "102", app_identifier: "com.AudiometerVideo.demo")
    upload_symbols_to_crashlytics(gsp_path: "/Users/arunjangid/Arun/Projects/Audiometer1April/Audiometer/Config/GoogleService-Info.plist")
    clean_build_artifacts           # Delete the local dSYM files
  end
end

